version: '3'

volumes:
  local:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: scheduler
    volumes:
      - .:/app
      - local:/app/local
    ports:
      - "5000:5000"
    tty: true